

jobs:
  - job: style
    displayName: Style linting
    strategy:
      matrix:
        stable:
          rust: stable
        beta:
          rust: beta
    pool:
      vmImage: ubuntu-18.04
    continueOnError: $[eq(variables.rust, 'beta')]
    steps:
      - template: install-rust.yml
        parameters:
          components:
            - rustfmt
            - clippy
      # Run any user-specific setup steps
      - script: cargo fmt --all -- --check
        workingDirectory: ${{ parameters.dir }}
        displayName: cargo fmt --check
      - script: cargo clippy --all
        workingDirectory: ${{ parameters.dir }}
        displayName: cargo clippy -- -D warnings